# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[time]
disabled = false
format = 'ğŸ•™ [$time]($style) '
time_format = '%T'
utc_time_offset = '-5'

[git_branch]
symbol = 'ïˆ  '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '\($count\)ğŸ³'
ahead = '\($count\)ğŸğŸ’¨'
behind = '\($count\)ğŸ˜°'
diverged = '\($ahead_countâ‡¡ $behind_countâ‡£\)ğŸ˜µ'
up_to_date = '[âœ“](green)'
untracked = '\($count\)ğŸ¤·'
stashed = '[\($count\)ğŸ“¦](white)'
modified = '[\($count\)ğŸ“](yellow)'
staged = '[\($count\)â•](green)'
renamed = '\($count\)ğŸ‘…'
deleted = '[\($count\)ğŸ—‘ ](red)'

